// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: notificationspb/message.proto

package notificationspb

import (
	any1 "github.com/golang/protobuf/ptypes/any"
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum representing message type.
// Protobuf enums use UPPER_SNAKE_CASE by convention.
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	MessageType_TYPE_ERROR               MessageType = 1
	MessageType_TYPE_INFO                MessageType = 2
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "TYPE_ERROR",
		2: "TYPE_INFO",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED": 0,
		"TYPE_ERROR":               1,
		"TYPE_INFO":                2,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_notificationspb_message_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_notificationspb_message_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_notificationspb_message_proto_rawDescGZIP(), []int{0}
}

// Base notification message.
type Message struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Type     MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=notifications.MessageType" json:"type,omitempty"`
	EntityId string                 `protobuf:"bytes,2,opt,name=entityId,proto3" json:"entityId,omitempty"`
	// Use Any for flexible/dynamic message content
	Message       *any1.Any `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_notificationspb_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_notificationspb_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_notificationspb_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *Message) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *Message) GetMessage() *any1.Any {
	if x != nil {
		return x.Message
	}
	return nil
}

// Message with a room field.
type MessageWithRoom struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Base  *Message               `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	// Room name is optional (nullable)
	Room          *string `protobuf:"bytes,2,opt,name=room,proto3,oneof" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageWithRoom) Reset() {
	*x = MessageWithRoom{}
	mi := &file_notificationspb_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageWithRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWithRoom) ProtoMessage() {}

func (x *MessageWithRoom) ProtoReflect() protoreflect.Message {
	mi := &file_notificationspb_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWithRoom.ProtoReflect.Descriptor instead.
func (*MessageWithRoom) Descriptor() ([]byte, []int) {
	return file_notificationspb_message_proto_rawDescGZIP(), []int{1}
}

func (x *MessageWithRoom) GetBase() *Message {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *MessageWithRoom) GetRoom() string {
	if x != nil && x.Room != nil {
		return *x.Room
	}
	return ""
}

// Message with a user ID field.
type MessageWithUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *Message               `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageWithUser) Reset() {
	*x = MessageWithUser{}
	mi := &file_notificationspb_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageWithUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWithUser) ProtoMessage() {}

func (x *MessageWithUser) ProtoReflect() protoreflect.Message {
	mi := &file_notificationspb_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWithUser.ProtoReflect.Descriptor instead.
func (*MessageWithUser) Descriptor() ([]byte, []int) {
	return file_notificationspb_message_proto_rawDescGZIP(), []int{2}
}

func (x *MessageWithUser) GetBase() *Message {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *MessageWithUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_notificationspb_message_proto protoreflect.FileDescriptor

const file_notificationspb_message_proto_rawDesc = "" +
	"\n" +
	"\x1dnotificationspb/message.proto\x12\rnotifications\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x85\x01\n" +
	"\aMessage\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.notifications.MessageTypeR\x04type\x12\x1a\n" +
	"\bentityId\x18\x02 \x01(\tR\bentityId\x12.\n" +
	"\amessage\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\amessage\"_\n" +
	"\x0fMessageWithRoom\x12*\n" +
	"\x04base\x18\x01 \x01(\v2\x16.notifications.MessageR\x04base\x12\x17\n" +
	"\x04room\x18\x02 \x01(\tH\x00R\x04room\x88\x01\x01B\a\n" +
	"\x05_room\"U\n" +
	"\x0fMessageWithUser\x12*\n" +
	"\x04base\x18\x01 \x01(\v2\x16.notifications.MessageR\x04base\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId*J\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"TYPE_ERROR\x10\x01\x12\r\n" +
	"\tTYPE_INFO\x10\x022\xe1\x01\n" +
	"\x13NotificationService\x12;\n" +
	"\tBroadcast\x12\x16.notifications.Message\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\n" +
	"NotifyRoom\x12\x1e.notifications.MessageWithRoom\x1a\x16.google.protobuf.Empty\x12G\n" +
	"\rPrivateNotify\x12\x1e.notifications.MessageWithUser\x1a\x16.google.protobuf.EmptyB\x13Z\x11./notificationspbb\x06proto3"

var (
	file_notificationspb_message_proto_rawDescOnce sync.Once
	file_notificationspb_message_proto_rawDescData []byte
)

func file_notificationspb_message_proto_rawDescGZIP() []byte {
	file_notificationspb_message_proto_rawDescOnce.Do(func() {
		file_notificationspb_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notificationspb_message_proto_rawDesc), len(file_notificationspb_message_proto_rawDesc)))
	})
	return file_notificationspb_message_proto_rawDescData
}

var file_notificationspb_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_notificationspb_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_notificationspb_message_proto_goTypes = []any{
	(MessageType)(0),        // 0: notifications.MessageType
	(*Message)(nil),         // 1: notifications.Message
	(*MessageWithRoom)(nil), // 2: notifications.MessageWithRoom
	(*MessageWithUser)(nil), // 3: notifications.MessageWithUser
	(*any1.Any)(nil),        // 4: google.protobuf.Any
	(*empty.Empty)(nil),     // 5: google.protobuf.Empty
}
var file_notificationspb_message_proto_depIdxs = []int32{
	0, // 0: notifications.Message.type:type_name -> notifications.MessageType
	4, // 1: notifications.Message.message:type_name -> google.protobuf.Any
	1, // 2: notifications.MessageWithRoom.base:type_name -> notifications.Message
	1, // 3: notifications.MessageWithUser.base:type_name -> notifications.Message
	1, // 4: notifications.NotificationService.Broadcast:input_type -> notifications.Message
	2, // 5: notifications.NotificationService.NotifyRoom:input_type -> notifications.MessageWithRoom
	3, // 6: notifications.NotificationService.PrivateNotify:input_type -> notifications.MessageWithUser
	5, // 7: notifications.NotificationService.Broadcast:output_type -> google.protobuf.Empty
	5, // 8: notifications.NotificationService.NotifyRoom:output_type -> google.protobuf.Empty
	5, // 9: notifications.NotificationService.PrivateNotify:output_type -> google.protobuf.Empty
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_notificationspb_message_proto_init() }
func file_notificationspb_message_proto_init() {
	if File_notificationspb_message_proto != nil {
		return
	}
	file_notificationspb_message_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notificationspb_message_proto_rawDesc), len(file_notificationspb_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notificationspb_message_proto_goTypes,
		DependencyIndexes: file_notificationspb_message_proto_depIdxs,
		EnumInfos:         file_notificationspb_message_proto_enumTypes,
		MessageInfos:      file_notificationspb_message_proto_msgTypes,
	}.Build()
	File_notificationspb_message_proto = out.File
	file_notificationspb_message_proto_goTypes = nil
	file_notificationspb_message_proto_depIdxs = nil
}
